#!/bin/bash

verbose="$1"
target="$2"
url="$URL"
id="$DISCORD_ID"

[ "$target"  = "" ] && target="chan"
[ "$verbose" = "" ] || verbose="v"

python3 ./fake.py "$url" "./csolve" "data/possible.txt" "$verbose" | python3 ./send_dc.py "$target" "$id"
